# Generated by Django 4.2.7 on 2024-01-23 14:06

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.TextField(default=profiles.models.genereteUUID),
        ),
    ]
