# Generated by Django 4.2.7 on 2024-01-24 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facelog',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 11, 4, 0, 0)),
        ),
        migrations.AlterField(
            model_name='facelog',
            name='day',
            field=models.SmallIntegerField(default='04'),
        ),
    ]
