# Generated by Django 4.2.7 on 2023-12-25 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='day',
            field=models.SmallIntegerField(default='04'),
        ),
        migrations.AddField(
            model_name='log',
            name='month',
            field=models.SmallIntegerField(default='10'),
        ),
        migrations.AddField(
            model_name='log',
            name='year',
            field=models.SmallIntegerField(default='1402'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 10, 4, 0, 0)),
        ),
    ]
