# Generated by Django 4.2.7 on 2023-12-28 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_log_daily_haziri_alter_log_date_alter_log_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 10, 7, 0, 0)),
        ),
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.SmallIntegerField(default='07'),
        ),
    ]
