# Generated by Django 4.2.7 on 2024-01-11 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_facelog_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facelog',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 10, 21, 0, 0)),
        ),
        migrations.AlterField(
            model_name='facelog',
            name='day',
            field=models.SmallIntegerField(default='21'),
        ),
    ]
