# Generated by Django 4.2.7 on 2023-11-14 13:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mudeeriath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mudeeriath_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('mudeeriath_name', models.CharField(max_length=40, unique=True)),
                ('mudeeriath_contact', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('mudeeriath_email', models.CharField(max_length=40)),
                ('date_joined', models.DateField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'مدیریت ',
            },
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('skoonath_asli', models.CharField(max_length=80)),
                ('skoonath_filee', models.CharField(max_length=80)),
                ('wazeefa', models.CharField(max_length=50)),
                ('qadam', models.CharField(max_length=15)),
                ('id_card', models.CharField(default='No', max_length=20)),
                ('dob', models.DateField()),
                ('pdo', models.CharField(max_length=20)),
                ('basth', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('mobile_aqarib', models.CharField(max_length=15)),
                ('mudeeriath', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hawala.mudeeriath')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'کنترولر',
                'unique_together': {('father_name', 'mudeeriath')},
            },
        ),
    ]
