# Generated by Django 4.2.7 on 2024-01-23 13:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hawala', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Haziri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.SmallIntegerField(choices=[(1, 'حمل'), (2, 'ثور'), (3, 'جوزا'), (4, 'سرطان'), (5, 'اسد'), (6, 'سنبله'), (7, 'میزان'), (8, 'عقرب'), (9, 'قوس'), (10, 'جدی'), (11, 'دلو'), (12, 'حوت')])),
                ('fiscalyear', models.SmallIntegerField(default=1402, null=True)),
                ('report_date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Close'), (1, 'Open'), (2, 'Suspended')], default=1)),
                ('created_by', models.CharField(max_length=22)),
                ('mudeeriath', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hawala.mudeeriath')),
            ],
            options={
                'unique_together': {('mudeeriath', 'month', 'fiscalyear')},
            },
        ),
        migrations.CreateModel(
            name='HowManyTimeHaziri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('times', models.SmallIntegerField(choices=[(1, 'ONE_PER_DAY'), (2, 'TWO_PER_DAY'), (3, 'ONE_PER_WEEK'), (4, 'TWO_PER_WEEK')], default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('total_present', 'total_present'), ('total_absent', 'total_absent'), ('total_leave', 'total_leave'), ('total_tafrihi', 'total_tafrihi'), ('total_zaroori', 'total_zaroori'), ('total_marizi', 'total_marizi'), ('total_waladi', 'total_waladi'), ('total_hajj', 'total_hajj')], max_length=50, null=True)),
                ('duration', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidTimeHaziri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('fromTime', models.TimeField(auto_now=True)),
                ('toTime', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Haziri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaifyath_haziri', models.TextField(blank=True, null=True)),
                ('total_present', models.SmallIntegerField()),
                ('total_absent', models.SmallIntegerField(default=0)),
                ('total_leave', models.SmallIntegerField(default=0)),
                ('total_tafrihi', models.SmallIntegerField(default=0)),
                ('total_zaroori', models.SmallIntegerField(default=0)),
                ('total_marizi', models.SmallIntegerField(default=0)),
                ('total_waladi', models.SmallIntegerField(default=0)),
                ('total_hajj', models.SmallIntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Close'), (1, 'Open'), (2, 'Suspended')], default=1)),
                ('haziri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haziri.haziri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'تفصیل حاضری',
            },
        ),
        migrations.CreateModel(
            name='General_Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('holiday', models.CharField(max_length=40)),
                ('status', models.BooleanField(choices=[(0, 'Close'), (1, 'Open')])),
            ],
            options={
                'verbose_name_plural': 'روزهای روخصتی',
                'unique_together': {('date', 'holiday')},
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_by', models.CharField(max_length=30)),
                ('month', models.SmallIntegerField(choices=[(1, 'حمل'), (2, 'ثور'), (3, 'جوزا'), (4, 'سرطان'), (5, 'اسد'), (6, 'سنبله'), (7, 'میزان'), (8, 'عقرب'), (9, 'قوس'), (10, 'جدی'), (11, 'دلو'), (12, 'حوت')], default=11)),
                ('year', models.SmallIntegerField(default=1402, null=True)),
                ('fromDay', models.SmallIntegerField(default=1)),
                ('toDay', models.SmallIntegerField(default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('leavetype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='haziri.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'رخصتی درخواستی',
                'unique_together': {('user', 'year', 'month', 'fromDay')},
            },
        ),
        migrations.CreateModel(
            name='Daily_Haziri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(1402, 11, 3, 0, 0))),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
