# Generated by Django 4.2.7 on 2023-11-29 09:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haziri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_haziri',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='daily_haziri',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='daily_haziri',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 9, 8, 0, 0)),
        ),
        migrations.AlterUniqueTogether(
            name='daily_haziri',
            unique_together={('user', 'date')},
        ),
    ]
