# Generated by Django 4.2.7 on 2023-12-11 13:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haziri', '0003_alter_daily_haziri_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Haziri_Details',
            new_name='Monthly_Haziri',
        ),
        migrations.AlterField(
            model_name='daily_haziri',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 9, 20, 0, 0)),
        ),
        migrations.AlterField(
            model_name='daily_haziri',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
