# Generated by Django 4.2.7 on 2023-12-14 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haziri', '0004_rename_haziri_details_monthly_haziri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haziri',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='haziri',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='daily_haziri',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 9, 22, 0, 0)),
        ),
    ]
