# Generated by Django 4.2.7 on 2023-12-14 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haziri', '0005_remove_haziri_end_date_remove_haziri_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_haziri',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 9, 23, 0, 0)),
        ),
    ]
