# Generated by Django 4.2.7 on 2023-12-14 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haziri', '0006_alter_daily_haziri_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('duration', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leave',
            name='fromDay',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leave',
            name='month',
            field=models.SmallIntegerField(choices=[(1, 'حمل'), (2, 'ثور'), (3, 'جوزا'), (4, 'سرطان'), (5, 'اسد'), (6, 'سنبله'), (7, 'میزان'), (8, 'عقرب'), (9, 'قوس'), (10, 'جدی'), (11, 'دلو'), (12, 'حوت')], default=9),
        ),
        migrations.AddField(
            model_name='leave',
            name='toDay',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leave',
            name='year',
            field=models.SmallIntegerField(default=1402, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='accepted_by',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together={('user', 'year', 'month', 'fromDay')},
        ),
        migrations.RemoveField(
            model_name='leave',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='start_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='leavetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='haziri.leavetype'),
        ),
    ]
