# Generated by Django 4.2.7 on 2023-12-28 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haziri', '0009_alter_daily_haziri_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howmanytimehaziri',
            name='per',
        ),
        migrations.AlterField(
            model_name='daily_haziri',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 10, 7, 0, 0)),
        ),
        migrations.AlterField(
            model_name='howmanytimehaziri',
            name='times',
            field=models.SmallIntegerField(choices=[(1, 'ONE_PER_DAY'), (2, 'TWO_PER_DAY'), (3, 'ONE_PER_WEEK'), (4, 'TWO_PER_WEEK')], default=1),
        ),
    ]
