# Generated by Django 4.2.7 on 2023-12-31 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haziri', '0010_remove_howmanytimehaziri_per_alter_daily_haziri_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_haziri',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 10, 9, 0, 0)),
        ),
    ]
