# Generated by Django 4.2.7 on 2024-01-11 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haziri', '0011_alter_daily_haziri_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly_haziri',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='daily_haziri',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 10, 21, 0, 0)),
        ),
    ]
