# Generated by Django 4.2.7 on 2024-01-13 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haziri', '0012_rename_user_id_monthly_haziri_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_haziri',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 10, 22, 0, 0)),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('total_present', 'total_present'), ('total_absent', 'total_absent'), ('total_leave', 'total_leave'), ('total_tafrihi', 'total_tafrihi'), ('total_zaroori', 'total_zaroori'), ('total_marizi', 'total_marizi'), ('total_waladi', 'total_waladi'), ('total_hajj', 'total_hajj')], max_length=50, null=True),
        ),
    ]
