# Generated by Django 4.2.7 on 2024-01-13 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haziri', '0013_alter_daily_haziri_date_alter_leavetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_haziri',
            name='date',
            field=models.DateField(default=datetime.datetime(1402, 10, 23, 0, 0)),
        ),
    ]
